### ISSUE TITLE
Update burn period tracker with new RAWS station climos

### ISSUE THREAD

**Issue by mcrimmins** [Climate-Science-Applications-Program/Burn-Period-Tracker#1]
- [x] get AZ, NM and other (?) state RAWS data to generate climo Rdata file
- [x] develop new burn period tracker master script/Rmarkdown file in this repo
- [x] run test on parallel directory on CSAP website
- [x] fix plot legend with red current, green forecast
